### ISSUE TITLE
Workers don't trigger on external assets because external assets do not build

### ISSUE THREAD

**Issue by Alireza-Iranpour** [trevorcampbell/fwirl#28]

**Comment by trevorcampbell** [comment]
Fixed in 34ff88d and 647f095 -- external assets now store a "pending value" when the call to timestamp notices an updated value, and the "pending value" only gets moved into the cache when `.build()` is called

Also needed 003f412 -- adds a rule to the refresh cascade that asserts that stale or failed (retry allowed) assets remain stale or failed. Only `.build()` can move them to be `AssetStatus.Current`

Together these two guarantee that when an `ExternalAsset` notices a difference, it will flag itself as `AssetStatus.Stale`, `refresh()` calls won't mess with that, so that `.build()` will rebuild the asset and update its status to `AssetStatus.Current` and trigger workers as expected
